server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此设置要绑定的rabbitMQ的服务信息
        defaultRabbit: #标识定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitMQ的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #通道名称
          destination: studyExchange #标识要使用的exchange 名称定义
          content-type: application/json #设置消息类型，本次为json，文本设置为“test/plain”
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: groupA


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    lease-expiration-duration-in-seconds: 5 #如果超过了5秒的间隔（默认是90秒）
    lease-renewal-interval-in-seconds: 2 #设置心跳间隔（默认是30秒）
    instance-id: receive-8803.com #信息列表中显示主机名称
    prefer-ip-address: true #访问的路径变为ip地址