server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  # gateway yml配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从服务注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh           #路由的ID，没有固定对着但要求唯一，建议配合服务名
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/cloud-payment-service/payment/get/**    #断言，路径相匹配的进行路由

        - id: payment_routh1           #路由的ID，没有固定对着但要求唯一，建议配合服务名
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/cloud-payment-service/payment/port/**    #断言，路径相匹配的进行路由
            # 路由匹配
            - After=2023-11-01T16:13:40.444+08:00[Asia/Shanghai] #断言，在此时间之后才能路由
            #- Before=2023-11-01T16:13:40.444+08:00[Asia/Shanghai] #断言，在此时间之前才能路由
            #- Between=2023-11-01T16:13:40.444+08:00[Asia/Shanghai],2023-11-01T16:13:40.444+08:00[Asia/Shanghai] #断言，在此时间中间才能路由
            #- Cookie=username,zzyy #断言，cookie携带参数username才能路由
            #- Header=X-Request-Id, \d+ #断言，header中携带参数，并且为整数才能路由
            #- Host=**.atguigu.com #断言，host中带有参数才能路由
            #- Method=GET #断言，get请求才能路由
            #- Query=username, \d+ #断言 要有参数名username，并且值还要是整数才能路由

eureka:
  client:
    # 表示是否将自己注册进eureka server 默认为true
    register-with-eureka: true
    # 表示是否从eureka server 抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    instance-id: gatewayService
    prefer-ip-address: true #访问路径可以显示IP地址
    # eureka客服端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-renewal-interval-in-seconds: 30