server:
  port: 80

eureka:
  client:
    register-with-eureka: false # 这个配置表示该应用不向Eureka注册自己，也就是说，它不会成为Eureka的服务提供者。
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版 这是Eureka服务器的默认区域，所有的服务都会注册到这个区域。

## 设置feign客户端超时时间（openFeign默认支持ribbon， 默认1秒）
ribbon:
  ReadTimeout: 5000 # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000 # 指的是建立连接后从服务器读取到可用资源所用的时间

feign:
  hystrix:
    enabled: true
  #设置 Feign 客户端超时时间
#  client:
#    config:
#      # default 表示全局配置，如要针对某个服务，则填写对应的服务名即可
#      default:
#        # Feign 客户端建立连接超时时间
#        connectTimeout: 10000
#        # Feign 客户端建立连接后读取资源超时时间
#        readTimeout: 10000

# Hystrix 配置
# 熔器断 Hystrix 的超时判断在 Feign 的超时判断时间，Hystrix默认超时时间是1秒
# 熔断器 Hystrix 的超时时间必须不小于 Feign 设置的超时时间，否则 Feign 设置的超时时间设置的超时时间无效
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

