server:
  port: 80

spring:
  application:
    name: consumer-feign-order80 # 应用名称


eureka:
  client:
    register-with-eureka: false # 这个配置表示该应用不向Eureka注册自己，也就是说，它不会成为Eureka的服务提供者。
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版 这是Eureka服务器的默认区域，所有的服务都会注册到这个区域。
  instance:
    instance-id: orderServer80 # 这是应用在Eureka中的实例ID，每个应用在Eureka中都有一个唯一的实例ID。
    prefer-ip-address: true # 这个配置表示在获取服务列表时，优先使用IP地址进行匹配，而不是使用主机名

# 设置feign客户端超时时间（openFeign默认支持ribbon， 默认1秒）
ribbon:
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign 日志以什么级别监控哪个接口
    com.test.springcloud.service.ConsumerFeignServer: debug
